### ISSUE TITLE
Error resolving $ref pointer Question

### ISSUE THREAD

**Issue by tayclark** [APIDevTools/swagger-parser#101]
Is it possible to continue validation when a $ref pointer SyntaxError exists? i.e. I may be referencing a definition that doesn't exist but I'd like to see other issues that the swagger contains instead of having to resolve the `$ref` and running another `validate()`

**Comment by JamesMessinger** [comment]
There's not currently a way to do that, but it's absolutely something that I'd like to add eventually.  Adding it to the to-do list 👍

**Comment by tayclark** [comment]
Thanks @JamesMessinger
