### ISSUE TITLE
Feature: Consider resolving references if they are relative from the main file

### ISSUE THREAD

**Issue by JehandadK** [APIDevTools/swagger-parser#103]
If the main file references a file which in turn references another file the reference should not be from root.

root.yaml, first/ref.yaml, second/ref.yaml

first/ref.yaml can reference schema 'A' as follows:

| Reference | Resolution Strategy | Supported In |
|:------------------------------------------:|---------------------------|----------------------------|
| '../second/ref.yaml#/components/schemas/A' | Relative from file itself | js parsers/ json-ref |
| './second/ref.yaml#/components/schemas/B' | Relative from root file | java parser/swagger-parser |

Would request considering support both. If not as a feature could there be a simple way to support both. Very troublesome to write spec usable by all tools.

**Comment by JamesMessinger** [comment]
While I understand how it could be useful to resolve all references against the root file, that is not in compliance with [the spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03).   `$ref` pointers are always resolved relative to the file in which they occur, just like `<a>` tags or `<img>` tags in an HTML file, or the `url()` function in a CSS file.

**Comment by JamesMessinger** [comment]
That said... if you _really_ want this behavior, then you can write a [custom resolver](https://apidevtools.org/json-schema-ref-parser/docs/plugins/resolvers.html) to do it.   Custom resolvers are a feature of [JSON Schema $Ref Parser](https://github.com/APIDevTools/json-schema-ref-parser), which is the library that Swagger Parser uses under the hood.  The `options` argument that you pass to any Swagger Parser method is passed-through to JSON Schema $Ref Parser, so custom resolvers work with Swagger Parser too.
