### ISSUE TITLE
Validation failed for object schema with patternProperties

### ISSUE THREAD

**Issue by ikokostya** [APIDevTools/swagger-parser#104]
**Versions**

* `Node.js`: 8.12.0
* `swagger-parser`: 6.0.2

**Code example**

Try to validate API specification where  `requestBody` schema is an `object` with [patternProperties](https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties):

```yaml
openapi: '3.0.2'
info:
  version: v1
  title: test
paths:
  /:
    post:
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
              patternProperties:
                '.+':
                  type: integer
      responses:
        200:
          description: Success
```

```js
const SwaggerParser = require('swagger-parser');

SwaggerParser.validate('api.yml')
  .then((api) => console.log('done'))
  .catch((err) => console.error(err));
```

**Expected behavior**

No error. The `patternProperties` property is allowed in JSON schema.

**Actual behavior**

The following validation error:

```
Data does not match any schemas from 'oneOf' at #/paths///post/requestBody
    Data does not match any schemas from 'oneOf' at #/paths///post/requestBody/content/application/json/schema
      Additional properties not allowed: patternProperties at #/content/application/json/schema
      Missing required property: $ref at #/content/application/json/schema
    Missing required property: $ref at #/paths///post/requestBody
```

**Comment by JamesMessinger** [comment]
The OpenAPI spec only supports a subset of JSON Schema.  `patternProperties` is one of the features that's not supported.  See [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject) for more details.

**Comment by ikokostya** [comment]
Thanks for explanation! Closing issue.
