### ISSUE TITLE
openapi-types needs to be a direct dependency for type definitions to work

### ISSUE THREAD

**Issue by zelein** [APIDevTools/swagger-parser#117]
![image](https://user-images.githubusercontent.com/2420177/59718830-9d57f580-91e0-11e9-92e3-605c59f8dd6a.png)

Openapi-types needs to be made a direct dependency so the type definitions can be properly resolved.

**Comment by zelein** [comment]
I can PR this in an hour or two if someone else hasn't gotten to it yet.

**Comment by ffflorian** [comment]
> I can PR this in an hour or two if someone else hasn't gotten to it yet, but this is going to break all TS projects upgrading to version 7.

They are broken anyway since everyone needs to install `openapi-types` manually.

**Comment by JamesMessinger** [comment]
Fixed via #118  👍
