### ISSUE TITLE
How to build a custom resolver?

### ISSUE THREAD

**Issue by vrrobz** [APIDevTools/swagger-parser#125]
The docs on this page:
https://apitools.dev/swagger-parser/docs/options.html
have several references to another doc that explains how t build a custom resolver (pointing to https://apitools.dev/swagger-parser/docs/plugins/resolvers.md). However, that page is totally empty.

I'd like to build a resolver that builds an OAS from a Github repo, which I assume will require a custom resolver as I'll be relying on the Github API to pull those files. .

**Comment by vrrobz** [comment]
Digging through surce code, looks like maybe the right docs are here? https://apitools.dev/json-schema-ref-parser/docs/plugins/resolvers.html

**Comment by vrrobz** [comment]
But reading that doc solves nothing for me - it shows me how to build the custom resolver, but not how to get the system to call it. So... how?

**Comment by vrrobz** [comment]
Good God, what an odyssey this was....

I figured it out, and for the sake of helping other folks, here's what I did:

In the options object you pass one of the SwaggerParser functions, you can specify custom parsers by adding an object with at least one key pointing to your special helper function like so:
```
    SwaggerParser.dereference(githubUrl, { resolve: { github: githubResolver }}, (err, api) => {
        if (err) {
          console.error(err);
          res.status(500).json(err);
        }
        else {
          res.send(api);
        }
    });
```

As mentioned in a previous comment, my goal here was to pull OpenAPI specs from Github and do something with them. So my helper looks like:

```
let githubResolver = {
    order: 1,
    canRead: /^github:/i,

    read(file, callback, $refs) {
        console.log("Parsing " + file.url);
        let full_path = file.url.replace(/github:\/\//, '');
        let path_parts = full_path.split('/');

        let spec_file = {};

        spec_file.owner = path_parts[0];
        spec_file.repo = path_parts[1];
        spec_file.ref = path_parts[2];
        spec_file.path = path_parts[3];
        for(let n = 4; n < path_parts.length; n++) {
            spec_file.path = path.join(spec_file.path, path_parts[n]);
        }

        octokit.repos.getContents({
            owner: spec_file.owner,
            repo: spec_file.repo,
            path: spec_file.path,
            ref: spec_file.ref
        })
        .then( function(result)  {
            if(!result.data) {
                console.log("Github returned empty data for repo: " + repo + "; path: " + spec_dir);
                callback(new Error("Github returned empty data for repo: " + repo + "; path: " + spec_dir));
            }
            if(Array.isArray(result.data)) {
                console.log("Github returned a directory instead of a file for: " + repo + "; path: " + spec_dir);
                callback(new Error("Github returned a single file instead of a directory for: " + repo + "; path: " + spec_dir));
            }
            if(!Array.isArray(result.data)) {
                let buf = Buffer.from(result.data.content, 'base64');
                let text = buf.toString('utf8');
                console.log("returning text");

                callback(null, text);
            }
        })
        .catch( function(error) {
            console.log(error);
            throw error;
        });
    }
};
```
Right now, it accepts a __very custom__ GitHub URL I create on the fly and pass to this function - mainly because I'm too lazy to mess with the URLs I get directly from Github. The format is "github://<repo-owner>/<repo-name>/<branch>/<path-to-file>". I parse that URL by splitting it and feeding it into the Octotkit REST JS library. 

I don't yet think this is properly dereferencing, so I'm testing that now. But that's outside the scope of this issue, so I'm considering it closed.

**Comment by JamesMessinger** [comment]
Ack!  Just now saw this thread.  Sorry about the broken links.  Will get those fixed right now.

As you already discovered, the _correct_ link is: https://apitools.dev/json-schema-ref-parser/docs/plugins/resolvers.html
