### ISSUE TITLE
Ref names are lost after parse

### ISSUE THREAD

**Issue by ftheomunhoz** [APIDevTools/swagger-parser#135]
After parse, the #ref from Definitions are resolved to its types, but their original names are lost.

Example:
https://petstore.swagger.io/v2/swagger.json

![image](https://user-images.githubusercontent.com/8484023/75162940-1eb34080-56fd-11ea-9bac-71260421dad4.png)

The `Pet` definition has an attribute named `category`, which has a #ref to the `Category` definition, but the reference is lost after parsing (even though the fields are parsed correctly). Its type should be `Category` instead of `object`.

**Comment by JamesMessinger** [comment]
I'm not sure I understand the problem.  Perhaps you're confusing the `parse()` method and the `dereference()` method.  Here's a code sample that demonstrates the differences between them:

https://runkit.com/bigstickcarpet/swagger-parser-issue-135

**Comment by ftheomunhoz** [comment]
You are absolutely correct, I found out the difference after meddling a bit after opening the issue. Although I was wondering if, even after derreferencing, at least a link to the original structure should be kept.

What I was expecting is a way where the value for `parsed.definitions.Pet.properties.category` is `Category`. This way, I can derrefence the structure myself whenever needed, sincr I'm using the parser to dynamically generate API code.

**Comment by JamesMessinger** [comment]
The `dereference()` method keeps referential integrity.  That is, it doesn't _copy_ objects, it references the existing object.  So after calling `dereference()`, the **same instance** of the `Category` object exists in two locations in the API definition.  The following comparison evaluates to `true`:

```
parsed.definitions.Category === parsed.definitions.Pet.properties.category
```

**Comment by ftheomunhoz** [comment]
That might indeed be enough. I wonder if this would still work of there were two identical structures in the definition list.  I will give it a try as soon as I get home and post the results so I have more practical arguments. Thank you for now.

**Comment by ftheomunhoz** [comment]
Ok, so I made the tests and you are absolutely correct. This is the runkit with the scenarios I created, just in case anyone has the same question as I did: https://runkit.com/ftheomunhoz/5e55a6cb3da6ee00144c74a8

Thank you again, you may close this issue.

**Comment by JamesMessinger** [comment]
I assume you're talking about the `definitions.Pet.properties.tags.items` value?  If so, then the reason it's not the same object is that it's defined as an "inherited" or "extended" object. 

```json5
"items": {
  "xml": {
    "name": "tag"
  },
  "$ref": "#/definitions/Tag" 
}
```

Because the "items" object contains both a `$ref` and other properties, it cannot be the same object instance.  It's a new object that includes all the properties of #/definitions/Tag _plus_ all the additional properties of "items"

**Comment by ftheomunhoz** [comment]
That's perfect, I get it, but in this case, how am I supposed to identify that `tags` is an array of `Tag`?

Also, I wad searching on the documentation and source but didn't find a way not to dereference the definitions during validation.

**Comment by JamesMessinger** [comment]
Hi.  Sorry for the delayed response.  My week got *really* busy.

In the "Tags" example, there is no way to determine that `tags` is an array of `Tag`, because _technically_ it's _not_ an array of `Tag`.  It's an array of an object that looks very much like `Tag` but has different properties.

If you want to prevent losing the reference to `Tag`, then I recommend using `allOf` to extend `Tag`.  Like this:

```json
"items": {
  "allOf": [
    { 
      "$ref": "#/definitions/Tag"
    }
  },
  "xml": {
    "name": "tag"
  },
}
```

Also, as you pointed out, the `validate()` method currently calls the `dereference()` method internally. This is [documented behavior](https://apitools.dev/swagger-parser/docs/swagger-parser.html#validateapi-options-callback), but I agree that it's a bit unintuitive. I hope to change this behavior in a future version.

**Comment by ftheomunhoz** [comment]
Don't worry, I get completely lost during the week sometimes as well :).

I was wondering if there couldn't be an option in the validate method, to keep the paths used by dereference. Does that make sense?

**Comment by JamesMessinger** [comment]
I'll have to think of some way of doing that without breaking changes.  Perhaps using a Symbol property instead of a normal property would work.

**Comment by ftheomunhoz** [comment]
Correct me if I'm wrong, but it looks like this should actually be implemented in the `json-schema-ref-parser` package, right? I was wondering if it should be handled in the `dereference` method, always adding a $ref property (even when it's not a circular structure).

Around here ([link](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/dereference.js#L122)).

**Comment by JamesMessinger** [comment]
Yeah, this would definitely be done in json-schema-ref-parser's `dereference` method

**Comment by maxtuzz** [comment]
Was thinking along the same lines.. I have a use case where de-referencing is incredibly useful for my programmatic flow, though now I need to be able to properly identity the name of the reference that has been de-referenced without having to do some cross field comparison craziness on components.schema.[refName]. 

+1 for an optional extra field as part of `BaseSchemaObject.properties`, if field is of type object or array.

**Comment by maxtuzz** [comment]
> without having to do some cross field comparison craziness on components.schema.[refName].
I did this as a quick workaround. @ftheomunhoz If you're still interested, I resolved a supplied dereferenced schema object to it's reference title with the following: 

```ts
import {OpenAPIV3} from "openapi-types";

class RefFinder {
    /**
     * Fetches the name of the schema that a suppliedSchema belongs to based on its property contents
     * @param suppliedSchema
     * @param components
     */
    static find(suppliedSchema: OpenAPIV3.SchemaObject, components: OpenAPIV3.ComponentsObject): string {
        if (suppliedSchema.type !== "object" || !suppliedSchema) {
            throw TypeError("Please supply schema of type object");
        }

        // Default schema ref title
        let schemaRefTitle: string = "object";

        const properties = suppliedSchema.properties
        if (!properties) {
            return schemaRefTitle;
        }

        // Get all field names from the supplied schema
        const fieldNames: string[] = Object.entries(properties).map(([key]) => key);

        const possibleSchemas = components?.schemas && Object.entries(components?.schemas);

        if (!possibleSchemas) {
            throw TypeError("No schema reference found")
        }


        for (const [schemaName, resource] of possibleSchemas) {
            const componentResource = resource as OpenAPIV3.SchemaObject;

            const refProps = componentResource.properties;

            // No properties, then continue to next iteration
            if (!refProps) {
                continue;
            }

            const found: boolean[] = Object.entries(refProps).map(([key]) => fieldNames.includes(key));

            if (found.every(Boolean)) {
                schemaRefTitle = schemaName;

                break;
            }
        }

        return schemaRefTitle;
    }
}

export default RefFinder;
```

It's not perfect, and doesn't handle array of object resolution but hopefully this can be helpful to someone. 

@JamesMessinger Is added a property still being considered? If so I don't mind looking at creating a PR.

**Comment by JamesMessinger** [comment]
@maxtuzz  - A possible solution was suggested by @wenerme in [Issue #173](https://github.com/APIDevTools/json-schema-ref-parser/issues/173).  I'd be interested in hearing people's opinions about it

**Comment by ftheomunhoz** [comment]
@JamesMessinger I answered in the other issue. That would certainly work as an alternative for us and wouldn't generate a breaking change.

**Comment by bcherny** [comment]
Commented on https://github.com/APIDevTools/json-schema-ref-parser/issues/173#issuecomment-663108134 with another motivating use case and a suggestion for how we might implement it.

**Comment by philsturgeon** [comment]
Let's merge these two threads and discuss in https://github.com/APIDevTools/json-schema-ref-parser/issues/173.
