### ISSUE TITLE
Cannot figure out how to use this module under webpack

### ISSUE THREAD

**Issue by zen0wu** [APIDevTools/swagger-parser#137]
Could we provide some official examples about how to config this module to be available under webpack?

**Comment by JamesMessinger** [comment]
What problem are you having?  We use Webpack for all of our browser tests and it works fine without any special configuration or anything. 

Please post your Webpack config, and the error you're getting

**Comment by dave-sapienza** [comment]
I've the same problem. 

This is my webpack config:
	
	let path = require("path");
	let webpack = require("webpack");
	const CopyPlugin = require("copy-webpack-plugin");

	module.exports = function(env) {

	let pack = require("./package.json");
	let MiniCssExtractPlugin = require("mini-css-extract-plugin");

	let production = !!(env && env.production);
	let asmodule = !!(env && env.module);
	let standalone = !!(env && env.standalone);

	let babelSettings = {
		extends: path.join(__dirname, "/.babelrc")
	};

	var config = {
		mode: production ? "production" : "development",
		entry: {
			app: "./sources/myapp.js"
		},
		output: {
			path: path.join(__dirname, "codebase"),
			publicPath:"/codebase/",
			filename: "[name].js",
			chunkFilename: "[name].bundle.js"
		},
		module: {
			rules: [
				{
					test: /\.js$/,
					use: `babel-loader?${  JSON.stringify(babelSettings)}`
				},
				{
					test: /\.(svg|png|jpg|gif)$/,
					use: "url-loader?limit=25000"
				},
				{
					test: /\.(less|css)$/,
					use: [ MiniCssExtractPlugin.loader, "css-loader", "less-loader" ]
				}
			]
		},
		stats:"minimal",
		resolve: {
			extensions: [".js"],
			modules: ["./sources", "node_modules"],
			alias:{
				"jet-views":path.resolve(__dirname, "sources/views"),
				"jet-locales":path.resolve(__dirname, "sources/locales")
			}
		},
		plugins: [
			new MiniCssExtractPlugin({
				filename:"[name].css"
			}),
			new webpack.DefinePlugin({
				VERSION: `"${pack.version}"`,
				APPNAME: `"${pack.name}"`,
				PRODUCTION : production,
				BUILD_AS_MODULE : (asmodule || standalone)
			}),
			new CopyPlugin({
				patterns: [
					{ from: path.resolve(__dirname, "index.html")},
					{ from: path.resolve(__dirname, "node_modules/@xbs/webix-pro/webix.css")},
					{ from: path.resolve(__dirname, "node_modules/@xbs/webix-pro/webix.js")},
					{ from: path.resolve(__dirname, "node_modules/@xbs/webix-pro/fonts"), to: "fonts"},
					{ from: path.resolve(__dirname, "node_modules/@xbs/webix-pro/skins"), to: "skins"},
					{ from: path.resolve(__dirname, "node_modules/@xbs/webix-pro/types"), to: "types"},
				],
			}),

		],
		devServer:{
			client: {
				logging: "error",
			},
			static: __dirname,
			historyApiFallback: true,
		}
	};

	if (!production){
		config.devtool = "inline-source-map";
	}

	if (asmodule){
		if (!standalone){
			config.externals = config.externals || {};
			config.externals = [ "webix-jet" ];
		}

		const out = config.output;
		const sub = standalone ? "full" : "module";

		out.library = pack.name.replace(/[^a-z0-9]/gi, "");
		out.libraryTarget= "umd";
		out.path = path.join(__dirname, "dist", sub);
		out.publicPath = `/dist/${sub}/`;
	}

	return config;
	};

and my errors are:

```
ERROR in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js 3:11-26
Module not found: Error: Can't resolve 'http' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (./sources, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

ERROR in ./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js 5:12-28
Module not found: Error: Can't resolve 'https' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

ERROR in ./node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js 13:0-36
Module not found: Error: Can't resolve 'url' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@apidevtools/json-schema-ref-parser/lib/util'
Did you mean './url'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (./sources, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

ERROR in ./node_modules/@apidevtools/swagger-parser/lib/options.js 9:11-26
Module not found: Error: Can't resolve 'util' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@apidevtools/swagger-parser/lib'
Did you mean './util'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (./sources, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

ERROR in ./node_modules/@apidevtools/swagger-parser/lib/util.js 3:11-26
Module not found: Error: Can't resolve 'util' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@apidevtools/swagger-parser/lib'
Did you mean './util'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (./sources, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

ERROR in ./node_modules/@jsdevtools/ono/esm/types.js 1:0-31
Module not found: Error: Can't resolve 'util' in '/Users/davidesammartino/Lavoro/repository/webapps/swaggerui/node_modules/@jsdevtools/ono/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

webpack 5.68.0 compiled with 6 errors in 10398 ms
```

**Comment by teone** [comment]
Has anyone solved this?

Just tried to include it in a React project created with (create-react-app)[https://github.com/facebook/create-react-app], simply doing (in the `App.js` file):
```
import SwaggerParser from '@apidevtools/swagger-parser'
```

 and I get:

```
Failed to compile.

Module not found: Error: Can't resolve 'http' in '/Users/mscandol/Sites/roc/roc-gui-experiments/roc-gui-react/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /Users/mscandol/Sites/roc/roc-gui-experiments/roc-gui-react/node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
WARNING in ./node_modules/@apidevtools/openapi-schemas/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/mscandol/Sites/roc/roc-gui-experiments/roc-gui-react/node_modules/@apidevtools/openapi-schemas/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/mscandol/Sites/roc/roc-gui-experiments/roc-gui-react/node_modules/@apidevtools/openapi-schemas/src/index.ts'
...
```

Any pointer on what needs to change?
I saw some older comments refencing a browser specific build under the `dist` folder, but that doesn't seems to be downloaded when getting the module with `npm install  @apidevtools/swagger-parser`.

**Comment by teone** [comment]
Update on my own question, as many have said this is due to Webpack 5 removing the polyfills, informations on how to add them back are here: https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a

What I did was:
1. `npm install --save stream-http https-browserify url util buffer
 process`
2. open the webpack configuration and look for `resolve`, then add a
```
fallback: {
        http: require.resolve("stream-http"),
        https: require.resolve("https-browserify"),
        url: require.resolve("url/"),
        util: require.resolve("util/"),
        buffer: require.resolve("buffer/"),
        process: require.resolve("process/browser")
      }
```
3. create a `polyfill.ts` (or if you are using Angular you can use the already existing one) and add:
```
import * as process from 'process';

(window as any).global = window;
(window as any).process = process;

// @ts-ignore
(window as any).Buffer = window.Buffer || require('buffer').Buffer;
```
_Note that this needs to be imported before you import `SwaggerParser`_

Hopefully this will help others having the same issue

**Comment by mortada-codes** [comment]
> Update on my own question, as many have said this is due to Webpack 5 removing the polyfills, informations on how to add them back are here: https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a
> 
> What I did was:
> 
> 1. `npm install --save stream-http https-browserify url util buffer  process`
> 2. open the webpack configuration and look for `resolve`, then add a
> 
> ```
> fallback: {
>         http: require.resolve("stream-http"),
>         https: require.resolve("https-browserify"),
>         url: require.resolve("url/"),
>         util: require.resolve("util/"),
>         buffer: require.resolve("buffer/"),
>         process: require.resolve("process/browser")
>       }
> ```
> 
> 3. create a `polyfill.ts` (or if you are using Angular you can use the already existing one) and add:
> 
> ```
> import * as process from 'process';
> 
> (window as any).global = window;
> (window as any).process = process;
> 
> // @ts-ignore
> (window as any).Buffer = window.Buffer || require('buffer').Buffer;
> ```
> 
> _Note that this needs to be imported before you import `SwaggerParser`_
> 
> Hopefully this will help others having the same issue

Thank you!

**Comment by shanti2530** [comment]
Thanks a lot @teone, your solution helped remove all of the compilation problems. However I am getting a new error in the browser 

`Uncaught TypeError: util.inherits is not a function at 63488 (options.js:35:6)`

The options.js file is Swagger-parser file. 

Did you or anyone else encounter this problem?

**Comment by stefanopog** [comment]
Sorry, i understand this is a very very basic question from a "beginner".

May someone please detail the steps from:
- clone the swager-parser repo

.... generate the webpack bundle (including eventually the webpack-config.js) 

-- provide the exact <script src="...." > definition to be used in my HTML file

-- explain how, in the javascript code I can IMPORT/REQUIRE/... the package and just create the "SwaggerParser" object ?

I know it is very very basic but this would help me understanding 

Thanks in advance
