### ISSUE TITLE
type: 'null' properties support in schemas

### ISSUE THREAD

**Issue by peter-plochan** [APIDevTools/swagger-parser#138]
Even it's not released yet, in [OpenAPI 3.1 Specification](https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#fixed-fields-20), there will be support for the `type: 'null'` property within schemas (see also [JSON Schema Draft 2019-09](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.4.2.1)). It seems that the parser doesn't support this for now because using [swagger-cli tool](https://github.com/APIDevTools/swagger-cli), the schema validation fails with the message:
```
Data does not match any schemas from 'oneOf' at #/paths//pets/{id}/put/requestBody/content/application/json/schema
      Data does not match any schemas from 'oneOf' at #/content/application/json/schema/properties/nullProp
        No enum match for: null at #/properties/nullProp/type
        Missing required property: $ref at #/properties/nullProp
      Missing required property: $ref at #/content/application/json/schema
    Missing required property: $ref at #/paths//pets/{id}/put/requestBody
```
I'm not sure how strict the parser (and its validation) would be, but it would be nice to support `"null"` type there. Thanks

**Comment by JamesMessinger** [comment]
Thanks for opening this ticket. There are several major changes in OpenAPI 3.1, and we're planning to start soon on supporting them all.

**Comment by seriousme** [comment]
@JamesMessinger OpenApi 3.1 has been released and the schema is available at:
https://github.com/OAI/OpenAPI-Specification/tree/master/schemas/v3.1

Anything we can do to help ?

**Comment by philsturgeon** [comment]
Let's track OAS3.1 work under #169.
