### ISSUE TITLE
exclusiveMaximum and exclusiveMinimum booleans or integers?

### ISSUE THREAD

**Issue by transitive-bullshit** [APIDevTools/swagger-parser#139]
For this OpenAPI v3 [spec](https://gist.github.com/transitive-bullshit/958b375dee20f9a92de6e7a7b481b157), which I believe to be valid, I get the following error:

```
SyntaxError {
    details: [
      {
        code: 'ONE_OF_MISSING',
        inner: Array [ … ],
        message: 'Data does not match any schemas from \'oneOf\'',
        params: [],
        path: Array [ … ],
        schemaId: undefined,
        [Symbol.for(z-schema/schema)]: Object { … },
        [Symbol.for(z-schema/json)]: Object { … },
      },
    ],
    toJSON: Function toJSON {},
    [Symbol.for(nodejs.util.inspect.custom)]: Function inspect {},
    message: `Swagger schema validation failed. ␊
      Data does not match any schemas from 'oneOf' at #/components/schemas/StyleCloudRequest␊
        Data does not match any schemas from 'oneOf' at #/components/schemas/StyleCloudRequest/properties/max_words␊
          Expected type boolean but found type integer at #/properties/max_words/exclusiveMinimum␊
          Missing required property: $ref at #/properties/max_words␊
        Missing required property: $ref at #/components/schemas/StyleCloudRequest␊
     ␊
    JSON_OBJECT_VALIDATION_FAILED`,
  }

  validateSchema (/Users/tfischer/dev/saasify/saasify/node_modules/@apidevtools/swagger-parser/lib/validators/schema.js:27:15)
  SwaggerParser.validate (/Users/tfischer/dev/saasify/saasify/node_modules/@apidevtools/swagger-parser/lib/index.js:155:7)
  test.js:25:5
  ZSchema.getLastError (/Users/tfischer/dev/saasify/saasify/node_modules/z-schema/src/ZSchema.js:260:13)
  validateSchema (/Users/tfischer/dev/saasify/saasify/node_modules/@apidevtools/swagger-parser/lib/validators/schema.js:25:23)
  SwaggerParser.validate (/Users/tfischer/dev/saasify/saasify/node_modules/@apidevtools/swagger-parser/lib/index.js:155:7)
  test.js:25:5
```

It seems the issue is that `swagger-parser` expects the `exclusiveMinimum` and `exclusiveMaximum` properties to be booleans which looks like was true for versions of JSON Schema <= v4 but this behavior changed in more recent versions of JSON schema to be integers (which makes more sense imho).

So my question is which version of JSON Schema does OpenAPI v3 support, or is it fuzzy at the moment? Should I assume that `exclusiveMinimum` and `exclusiveMaximum` are booleans for the purposes of OpenAPI going forwards?

Thanks!

**Comment by JamesMessinger** [comment]
OpenAPI v3.0 is based on [JSON Schema Specification Wright Draft 00](https://tools.ietf.org/html/draft-wright-json-schema-validation-00), which is an older version of JSON Schema from 2016.  There have been a few [versions of JSON Schema since then](https://json-schema.org/specification-links.html), but OpenAPI 3.0 is still pinned to the 2016 version.

In that version of JSON Schema, `exclusiveMinimum` and `exclusiveMaximum` are booleans, not integers.

**This will be changing in OpenAPI 3.1**, which will release later this year. OpenAPI 3.1 is based on the latest version of JSON Schema, which is [2019-09](https://json-schema.org/specification.html)

**Comment by transitive-bullshit** [comment]
Awesome -- makes total sense.

Thanks for the quick response & all the great work, James!
