### ISSUE TITLE
Supports to parse multi spec files

### ISSUE THREAD

**Issue by brelian** [APIDevTools/swagger-parser#147]
# 🚀 feature request

### Description
Sometimes, there are many APIs in our application. It's hard to maintain in one specification (yaml file). In this case, we normally split it into many files. Shall we consider supporting to parse multi spec files?

### Suggestion solution
For instance, there are 1 spec files,
```shell
.
├── comment.yaml
├── swagger.yaml
└── user.yaml
```
I think we could parse all files and merge them into one Swagger Object, then we parse, dereference, validate the Swagger Object just like what we are doing now.

**Comment by JamesMessinger** [comment]
This feature is already supported.  Swagger Parser will read and merge any number of files, including files of different types (JSON, YAML, etc.)

**Comment by brelian** [comment]
> This feature is already supported. Swagger Parser will read and merge any number of files, including files of different types (JSON, YAML, etc.)

Cool, James. Could I help do something if need it? I'm a JavaScript/TypeScript developer.

**Comment by brelian** [comment]
> This feature is already supported. Swagger Parser will read and merge any number of files, including files of different types (JSON, YAML, etc.)

Thanks James. It's already done, right? If so I think this issue could be closed.
