### ISSUE TITLE
openapi-types versioning

### ISSUE THREAD

**Issue by badsyntax** [APIDevTools/swagger-parser#150]
hi. I'm using this package as well as `openapi-types` in my typescript project. in order for the typechecking of the exported types of `openapi-types` to work correctly, both my project and `swagger-parser` need to be referencing the same types. if i install the  exact same version of `openapi-types` as the one consumed by `swagger-parser`, npm will dedupe the duplicated directories and everything is fine. if i use a different version of `openapi-types` then typechecking won't work correctly. 

so there's 2 things here:

1. should `openapi-types` be a `peerDependency` instead of a direct `dependency`? at least this will force the consumer to install the matching version of `openapi-types` in their project.
2. if no to point 1, can you upgrade `openapi-types` to a more recent version? (currently on [7.0.1](https://www.npmjs.com/package/openapi-types))

**Comment by JamesMessinger** [comment]
You bring up a good point.  `openapi-types` was originally added as a dependency to resolve [Issue #117](https://github.com/APIDevTools/swagger-parser/issues/117), but perhaps a peerDependency would have been a better choice. 🤔 

I'd be curious what @nickzelei and @ffflorian think about making this change

**Comment by nickzelei** [comment]
My suggestion would be to move `openapi-types` to being a peer dependency. This forces the consumer to install the correct version, and allows them to freely upgrade the types package to satisfy the semver range that `swagger-parser` has selected as its compatible range.

**Comment by ffflorian** [comment]
I agree with @nickzelei :)

**Comment by JamesMessinger** [comment]
This change has been made and published as v10.0.2

**Comment by badsyntax** [comment]
Awesome thanks!

**Comment by argos83** [comment]
I believe this should have been released as a major version, this change broke a bunch of our master builds.

**Comment by JamesMessinger** [comment]
@argos83 - Sorry about that! It's sometimes hard to determine what should be a major version bump, since just about anything in JavaScript can be a breaking change 😰
