### ISSUE TITLE
z-schema vulnerability

### ISSUE THREAD

**Issue by isatria** [APIDevTools/swagger-parser#172]
Vulnerability: 
- [SRCCLR-SID-29395](https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-29395/summary) Medium severity
- [SRCCLR-SID-30061](https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-30061/summary) Medium severity
Dependency: validator

|─┬ swagger-parser@8.0.4
|─└┬ z-schema@^4.2.2
|──└┬ validator@^12.0.0

Do you have a schedule to update the `z-schema` to v5.0.1 anytime soon?

it's causing a medium severity vulnerability since `^4.2.2` still using the validator@^12.0.0.

**Comment by philsturgeon** [comment]
Done, we'll get a version released when main branch is passing tests.
