### ISSUE TITLE
swagger-parser `10.0.3` version is not compatible with `typescript` version `4.4.2`

### ISSUE THREAD

**Issue by jjtang1985** [APIDevTools/swagger-parser#186]
## Description
Dependabot created a [PR](https://github.com/SAP/cloud-sdk-js/pull/1561) for updating `typescript` version to `4.4.2`, which failed due to the error below:

```
TypeError: Class is not a constructor

    at resolve (/.../node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:162:18)
```

## How to reproduce
1. update `typescript` version to `4.4.2`.
2. run the following code and see errors
```typescript
  async resolve(document); // typed as `OpenAPIV3.Document`
```

## Expected behaviour
The type error is fixed.

## Additional information
It's working with `typescript` version `4.3.5`.

**Comment by milesj** [comment]
Has anyone figured out a work around?

**Comment by nspire909** [comment]
To fix this after updating to Angular 13 and TS 4.4, I just changed from importing an individual method to the entire object:

`import { validate } from '@apidevtools/swagger-parser';` 
to 
`import $SwaggerParser from '@apidevtools/swagger-parser';`

And then use `$SwaggerParser.validate` instead of `validate`.

**Comment by philsturgeon** [comment]
Can somebody send a pull request if you've figured the problem out?

**Comment by FrankEssenberger** [comment]
We used the following work around in our project: 
https://github.com/SAP/cloud-sdk-js/blob/main/packages/openapi-generator/src/parser/swagger-parser-workaround.ts
This sets the `this` pointer to the `SwaggerParser` and the old code works. Either you would have to wrap the public facing methods with something similar or you need to adjust the code that it does not use the `this` pointer the way it does currently.

**Comment by philsturgeon** [comment]
@FrankEssenberger thanks frank. I'd really appreciate it if you could find some time to send a pull request moving your workaround upatream as a solution. I am technically maintaining this project but I've never used it in my life, and I've already put about 10 hours into try fix the release process and various dependencies that are causing troubles, unpaid, just as a favor to the previous owner. If you've got tooling which uses this tool it would be awesome to help me get it fixed. 🙌🏻
