### ISSUE TITLE
swagger version field as 'number' type is not detected in one case

### ISSUE THREAD

**Issue by nathcarmona** [APIDevTools/swagger-parser#226]
I have noticed that the validator does not check for the **type** of "version" in a swagger file when it has major, minor and patch versions. 

```openapi: 3.0.2
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.0
```

When the version is of type number and `version: 1.0` or `version: 1`, an error is thrown "API version number must a string (e.g. "1.0.0") not a number", but the error does not appear when `version: 1.0.0`.

**Comment by philsturgeon** [comment]
Thats thanks to YAML considering that a string. 🙌🏻
