### ISSUE TITLE
validator doesn't support anchor tags in the paths (ie /my/base/url#myAnchor)

### ISSUE THREAD

**Issue by normana400** [APIDevTools/swagger-parser#245]
anchor tags are considered part of the url and technically within the spec of a valid url. 
I support active systems in production that successfully work with a swagger files that uses anchor tags, but this validator rejects them.

**Comment by normana400** [comment]
in case you may wonder why a swagger url would have anchor tags in it, you can use anchor tags as part of a solution to to describe a "rest level 0" RPC type system successfully within the swagger requirements.

**Comment by philsturgeon** [comment]
This is true! This is an old OpenAPI v3.0 based system, if you want something modern please go pick something from https://openapi.tools. 

The valdation/linting in https://github.com/Redocly/redocly-cli/ is a lot better.
