### ISSUE TITLE
Not able to parse stripe openapi file

### ISSUE THREAD

**Issue by saireddy12** [APIDevTools/swagger-parser#247]
I am using this library in a javascript file and trying to run it using python 

the library is able to parse many of the openapi files correctly but its taking forever to process Stripe openapi file 
https://api.apis.guru/v2/specs/stripe.com/2022-11-15/openapi.json 

I am using the below in a javascript function  
const api = await SwaggerParser.dereference(inputFilePath)

Installed the library using `npm install @apidevtools/swagger-parser`

Fyi , i did check this and installing the old version didn't help 
https://github.com/APIDevTools/swagger-parser/issues/221

Please let me know , if i am doing something wrong.

Thanks.!

**Comment by sudhanshug16** [comment]
Hey, did you figure out a solution to this? I am also stuck parsing stripe's OpenAPI

**Comment by vcs-dev** [comment]
> I am using this library in a javascript file and trying to run it using python
> 
> the library is able to parse many of the openapi files correctly but its taking forever to process Stripe openapi file https://api.apis.guru/v2/specs/stripe.com/2022-11-15/openapi.json
> 
> I am using the below in a javascript function const api = await SwaggerParser.dereference(inputFilePath)
> 
> Installed the library using `npm install @apidevtools/swagger-parser`
> 
> Fyi , i did check this and installing the old version didn't help #221
> 
> Please let me know , if i am doing something wrong.
> 
> Thanks.!

Hello.

Try this way:
`import SwaggerParser from '@apidevtools/swagger-parser';

const parser= new SwaggerParser();

const getDereferencedApi(async () => {
  await parser.dereference(path to your json file); //The path can be also a url.
  console.log(parser.api);
});`

If the problem persists, check the reading permission of your json file.

I hope this helps.
