### ISSUE TITLE
Update OpenAPI 3.0.0 to OpenAPI 3.1

### ISSUE THREAD

**Issue by inayet** [APIDevTools/swagger-parser#249]
Are there plans to updating this code to Update OpenAPI 3.0.0 to OpenAPI 3.1? Or a new tool that can take care of that?

**Comment by philsturgeon** [comment]
There are no plans to add any migration functionality to this package, in fact its winding down (even the name is out of date!) 

You can use this package to help with upgrades around schemas, which is the main difference. 

https://github.com/openapi-contrib/json-schema-to-openapi-schema/

For the rest, heres a guide.

https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by inayet** [comment]
Thank you @philsturgeon , I started on a project on github to transform OpenAPI 3.0.0 to OpenAPI 3.1.0 works okay but a lot of improvement is needed https://github.com/inayet/openapi30_to_openapi31
