### ISSUE TITLE
Not possible to have "allOf" definitions merged?

### ISSUE THREAD

**Issue by Kitanotori** [APIDevTools/swagger-parser#51]
Is it not possible to destructure "allOf" array? I want the object definitions in the array be merged into a single "properties" object.

**Comment by BigstickCarpet** [comment]
This feature was considered previously, but I decided not to implement it because it wouldn't comply with the spec.  See https://github.com/BigstickCarpet/json-schema-ref-parser/issues/1#issuecomment-145652500

**Comment by Kitanotori** [comment]
It may not comply with the spec, but I have a bunch of dependencies that are failing because they have no idea how to handle "allOf". I figured it would be easiest if I could just merge them using swagger-parser. Wouldn't it be possible even to add an experimental feature for the purpose?

**Comment by BigstickCarpet** [comment]
I'm going to re-open this issue to serve as a feature request.  I'm currently working on a new version of Swagger Parser that will allow third-party plug-ins that add functionality exactly like this.  I'll probably go ahead and create a plugin that does this, since multiple people have asked for it, and it'll be a good demonstration of how to author plug-ins.

**Comment by jcdarwin** [comment]
@BigstickCarpet Just wondering if you've made any progress on implementing the third-party plugin  system for the new Swagger parser, and the plugin for allowing the merge of AllOf definitions?

We're very keen to use this once it's available.

**Comment by BigstickCarpet** [comment]
@jcdarwin - I haven't had a chance to work on it yet.  A few other projects have needed my time instead.  But soon!  :)

**Comment by copitz** [comment]
Stumbled upon this also on BigstickCarpet/swagger-express-middleware#102

**Comment by sepiol** [comment]
> @jcdarwin - I haven't had a chance to work on it yet. A few other projects have needed my time instead. But soon! :)

Is that still under consideration?

**Comment by rkrauskopf** [comment]
@sepiol, our next priority is adding support for OpenAPI v3.

**Comment by lucasassisrosa** [comment]
> @jcdarwin - I haven't had a chance to work on it yet. A few other projects have needed my time instead. But soon! :)

any updates on this?

**Comment by philsturgeon** [comment]
Gotta respect the spec. If tools don't know what allOf is they need to be updated.

**Comment by Fruetel** [comment]
> Gotta respect the spec. If tools don't know what allOf is they need to be updated.

Why did you close the issue then? Is this library going to be updated with regards to `allOf`?

**Comment by philsturgeon** [comment]
It's not going to be built.
