### ISSUE TITLE
Synchronous evaluation

### ISSUE THREAD

**Issue by ksmithut** [APIDevTools/swagger-parser#54]
Have there been any thoughts about a synchronous api? I'm currently using swagger-parser to dereference a swagger api definition and then using the resolved one to make api validation middleware. This definition could of course be made asynchronously, but for the purpose of doing an initial setup, doing it asynchronously means some inflexibility or slight performance issues on hot (request time) code. No pressure if you just flat out don't want to support it, I was just curious.

**Comment by BigstickCarpet** [comment]
Hi.  I'm still planning to implement a synchronous API at some point, but I just haven't had the time yet.  Been working on a million other things, and there just doesn't seem to be enough time in the day :-/

**Comment by ksmithut** [comment]
I don't have an exorbitant amount of time, but I think I could find some time over the next couple of weeks to work in a pull request, unless you already have an idea to implement it.

**Comment by BigstickCarpet** [comment]
Most of the logic (and API) of Swagger Parser is actually implemented in [JSON Schema $Ref Parser](https://github.com/BigstickCarpet/json-schema-ref-parser), which is another repo of mine.  However, Swagger Parser currently uses an old version of JSON Schema $Ref Parser (v1.4), and it _really_ needs to be upgraded to the latest version (v4.0).

But JSON Schema $Ref Parser v4.0 isn't actually released yet.  It's about 95% finished, but then I got sidetracked on other stuff and never got a chance to finish it.    

So, if you want to take a stab at implementing a synchronous API, the place to do it is in [the v4.0 branch of JSON Schema $Ref Parser](https://github.com/BigstickCarpet/json-schema-ref-parser/tree/releases/4.0.0).

**Comment by ksmithut** [comment]
Awesome, I'll take a look :)

**Comment by gkoberger** [comment]
This would be great to have. Makes it really hard for us to use `swagger-parser` without it.

**Comment by MikeTaylor** [comment]
Did anything come of this?

**Comment by philsturgeon** [comment]
Gonna hope async/await is good enough for now, or you can at least make some wrappers.
