### ISSUE TITLE
Webpack compile issue

### ISSUE THREAD

**Issue by smile18** [APIDevTools/swagger-parser#63]
I have installed `swagger-parser@3.4.1` and trying to validate my api using `parser.validate("swaggerJson")` but getting webpack compile issue 

Here is the code ...

    SwaggerParser = require('swagger-parser');
     validateResult: string;
     swaggerSpec ;

    constructor(private http: Http, private service: DifferencesService){
       let  parser = new this.SwaggerParser();
       service.getSwaggerSpec().subscribe(
        result => { this.swaggerSpec = result;},
        error => { console.log(error); }
      );
     parser.validate(this.swaggerSpec)
      .then(function(api) {
        this.validateResult = "Yay! The API is valid.";
        console.log('Yay! The API is valid.');
      })
      .catch(function(err) {
        this.validateResult = 'Onoes! The API is invalid. ' + err.message;
        console.error('Onoes! The API is invalid. ' + err.message);
      });

Here is the Error ...

    ERROR in ./~/swagger-parser/lib/validate-schema.js
    Module not found: Error: Can't resolve 'swagger-schema-official/schema' in 'D:\gitmyworkspace\mywork\pcfdeploy\node_modules\swagger-parser\lib'
    @ ./~/swagger-parser/lib/validate-schema.js 6:20-61
    @ ./~/swagger-parser/lib/index.js
    @ ./src/app/components/swagger-validate.component.ts
    @ ./src/app/app.module.ts
    @ ./src/main.ts
    @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
    ERROR in ./~/swagger-parser/lib/promise.js
    Module not found: Error: Can't resolve 'es6-promise' in 'D:\gitmyworkspace\mywork\pcfdeploy\node_modules\swagger-parser\lib'
    @ ./~/swagger-parser/lib/promise.js 4:59-81
    @ ./~/swagger-parser/lib/index.js
    @ ./src/app/components/swagger-validate.component.ts
    @ ./src/app/app.module.ts
    @ ./src/main.ts
    @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

    ERROR in ./~/json-schema-ref-parser/lib/promise.js
    Module not found: Error: Can't resolve 'es6-promise' in 'D:\gitmyworkspace\mywork\pcfdeploy\node_modules\json-schema-ref-parser\lib'
    @ ./~/json-schema-ref-parser/lib/promise.js 4:59-81
    @ ./~/json-schema-ref-parser/lib/index.js
    @ ./~/swagger-parser/lib/index.js
    @ ./src/app/components/swagger-validate.component.ts
    @ ./src/app/app.module.ts
    @ ./src/main.ts
    @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
    webpack: Failed to compile.

**Comment by BigstickCarpet** [comment]
I suspect that WebPack is attempting to load Swagger Parser as a Node.js module rather than a browser module.  Try pointing WebPack directly to [the browser distributable file](https://github.com/BigstickCarpet/swagger-parser/blob/master/dist/swagger-parser.js) instead.

**Comment by smile18** [comment]
I am not sure how to point to browser distributed file, I am using this in my `Angular2` with `Angular-Cli`, please let me know where and how to point Webpack to the browser distributed file. Thanks.

**Comment by BigstickCarpet** [comment]
I'm not a Webpack user, so I don't know how to point it to a specific file.  But there must be a way to do it, because it's pretty common for Node.js modules to also have a separate browser distributable file.

**Comment by smile18** [comment]
I have pointed to the browser distributed file by adding it in `angular-clli.json` where I have pointed for other js files


     "scripts": [
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/swagger-parser/dist/swagger-parser.js"
      ],


Here is my `SwaggerComponent`


	export class SwaggerValidateComponent {
		SwaggerParser = require('swagger-parser');
		validateResult: string;
		swaggerSpec ;

		constructor(private http: Http, private service: DifferencesService){
			let  parser = new this.SwaggerParser();
			service.getSwaggerSpec().subscribe(
			result => {
			this.swaggerSpec = result;},
			error => {}
		);

		parser.validate(this.swaggerSpec).then(function(api) {
			this.validateResult = "Yay! The API is valid.";
		})
		.catch(function(err) {
        this.validateResult = 'Onoes! The API is invalid. ' + err.message;
		});
		}

		getSwaggerSpec(){
		return this.http.get('../assets/resources/SwaggerSpec.json').map( genres => {
			return genres.json();
		}).catch((error: any):any => {
		return Observable.throw(error.json().error || 'Server error');
		})
	}

**Comment by yuejiaozhs** [comment]
I got the same error and my solution is: 
"`import * as SwaggerParser from 'swagger-parser/dist/swagger-parser';`". 
Inspired by: https://github.com/BigstickCarpet/swagger-parser/issues/48. It works in my project, wish it can help you.
