### ISSUE TITLE
Circular dependency warnings

### ISSUE THREAD

**Issue by fix-me** [APIDevTools/swagger-parser#98]
Hi,

I'm using swagger-parser module in a rollupJS library with the commonjs plugin.
Several circular dependencies appear while build process:

```
(!) Circular dependency: node_modules\z-schema\src\SchemaCache.js -> node_modules\z-schema\src\SchemaCompilation.js -> node_modules\z-schema\src\SchemaCache.js
(!) Circular dependency: node_modules\z-schema\src\SchemaCache.js -> node_modules\z-schema\src\SchemaCompilation.js ->  commonjs-proxy:***\node_modules\z-schema\src\SchemaCache.js -> node_modules\z-schema\src\SchemaCache.js
(!) Circular dependency: node_modules\json-schema-ref-parser\lib\ref.js -> node_modules\json-schema-ref-parser\lib\pointer.js -> node_modules\json-schema-ref-parser\lib\ref.js
(!) Circular dependency: node_modules\json-schema-ref-parser\lib\ref.js -> node_modules\json-schema-ref-parser\lib\pointer.js ->  commonjs-proxy:***\node_modules\json-schema-ref-parser\lib\ref.js -> node_modules\json-schema-ref-parser\lib\ref.js
```

Greetz!

**Comment by James-Messinger** [comment]
Circular dependencies between modules are allowed in JavaScript.   If Rollup throws errors on circular dependencies, then that's a bug in Rollup.  

That said... I bet there's a way to get Rollup to work.  Maybe there's an option or a plugin or something.  I'm not very familiar with Rollup, so I don't know.

**Comment by James-Messinger** [comment]
It appears that this is a known issue in Rollup

https://github.com/nodejs/readable-stream/issues/348

**Comment by fix-me** [comment]
Oh, I see its a problem with cjs modules which get lifted to es static imports.
So it's more related to the commonJS plugin, I'll try my best there.

Thank you!
